import type { Metadata } from "next";

import Footer from "@/components/shared/Footer";
import Header from "@/components/layout/Header";
import Testimonials from "@/components/shared/Testimonials";
import TrustSection from "@/components/home/TrustSection";

import styles from "./AboutUs.module.css";
import FixedCta from "@/components/layout/FixedCta";

export const metadata: Metadata = {
  title: "TASK Holidays",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png",
    shortcut: "/favicon.png",
    apple: "/favicon.png",
  },
};

const AboutUs = () => {
  return (
    <>
      <Header navItems={[]} isRelative={true} />
      <main className={` section_white__spacing`}>
        <section>
          <div className={` container `}>
            <h1 className={styles.aboutus_heading}>About Us</h1>
            <p className={styles.aboutus_content}>
              Welcome to Task Holidays, your trusted travel partner for creating
              unforgettable journeys and meaningful travel experiences. We
              believe that travel is not just about reaching a destination — it
              is about discovering new places, experiencing different cultures,
              and creating memories that stay with you for a lifetime.
            </p>
            <p className={styles.aboutus_content}>
              At Task Holidays, our mission is to make travel simple,
              comfortable, and enjoyable for every traveller. With a passion for
              exploration and a commitment to quality service, we design
              carefully planned travel experiences that combine convenience,
              comfort, and adventure.
            </p>
            <p className={styles.aboutus_content}>
              Our team of travel experts works closely with travellers to
              understand their preferences and create personalized travel
              experiences that match their expectations. From the moment you
              start planning your trip until you return home, we ensure every
              detail of your journey is managed with professionalism and care.
            </p>
            <p className={styles.aboutus_content}>
              We provide a complete range of travel services including holiday
              packages, group tours, customized trips, hotel bookings,
              transportation services, and travel assistance. Our focus is
              always on delivering reliable services, transparent pricing, and
              excellent customer support so that travellers can explore the
              world without stress.
            </p>
            <p className={styles.aboutus_content}>
              Task Holidays specializes in some of the most popular travel
              destinations, including Bali, Thailand, Ladakh, Sri Lanka,
              Andaman, and Kerala. With our strong travel partnerships and
              experience in these destinations, we are able to offer carefully
              curated travel packages at some of the best rates in the market
              while maintaining high standards of comfort and service.
            </p>
            <p className={styles.aboutus_content}>
              What makes Task Holidays different is our dedication to customer
              satisfaction and our belief that every journey should be special.
              Whether you are planning a relaxing vacation, a family holiday, a
              honeymoon, or a group travel experience, we aim to deliver
              seamless travel solutions that exceed expectations.
            </p>
            <p className={styles.aboutus_content}>
              At Task Holidays, we do not simply arrange trips — we craft travel
              experiences that inspire, connect, and create lasting memories.
            </p>
            <div className="empty_space" />
            <h6 className={styles.aboutus_heading}>Our Vision</h6>
            <p className={styles.aboutus_content}>
              To become one of the most trusted and customer-focused travel
              service providers by delivering exceptional travel experiences and
              reliable services.
            </p>
            <div className="empty_space" />
            <h6 className={styles.aboutus_heading}>Our Mission</h6>
            <p className={styles.aboutus_content}>
              To provide well-planned, affordable, and memorable travel
              experiences while maintaining the highest standards of service and
              customer satisfaction.
            </p>
          </div>
        </section>
      </main>
      <Testimonials />
      <TrustSection />
      <Footer />
      <FixedCta />
    </>
  );
};

export default AboutUs;
