import type { Metadata } from "next";
import styles from "./TermsConditions.module.css";
import Footer from "@/components/shared/Footer";
import Header from "@/components/layout/Header";
import TermsConditionsData from "@/components/tnc/TermsConditionsData";

export const metadata: Metadata = {
  title: "TASK Holidays",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png",
    shortcut: "/favicon.png",
    apple: "/favicon.png",
  },
};

const TermsConditionsPage = () => {
  return (
    <>
      <Header navItems={[]} supportClassName="isRelative__header" />
      <main className={`${styles.tnc} section_white__spacing`}>
        <section className={`${styles.tnc__hero}`}>
          <div className={`${styles.tnc__container} container `}>
            <h1 className={styles.tnc__title}>
              Premium Travel – Terms & Conditions
            </h1>
            <p className={styles.tnc__subtitle}>
              Please read these terms carefully before confirming your travel
              with TASK Holidays.
            </p>
          </div>
        </section>

        <section className={styles.tnc__content}>
          <div className={`${styles.tnc__container} container`}>
            <TermsConditionsData />
          </div>
        </section>
      </main>
      <Footer />
    </>
  );
};

export default TermsConditionsPage;
