import type { Metadata } from "next";
import styles from "./TermsConditions.module.css";
import Footer from "@/components/shared/Footer";
import Header from "@/components/layout/Header";

export const metadata: Metadata = {
  title: "TASK Holidays",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png",
    shortcut: "/favicon.png",
    apple: "/favicon.png",
  },
};

type TncItem = {
  id: number;
  title: string;
  content: string[];
};

const tncData: TncItem[] = [
  {
    id: 1,
    title: "Payment & Confirmation",
    content: [
      "To ensure seamless planning and preferred availability, 50% of the total package value is required at the time of confirmation for domestic travel.",
      "The remaining balance must be settled 30 days prior to departure.",
      "International travel payment schedules may vary and will be clearly communicated before confirmation. In the absence of specific communication, domestic payment terms shall apply.",
      "Non-refundable accommodations require full advance payment at the time of booking.",
    ],
  },
  {
    id: 2,
    title: "Cancellations & Amendments",
    content: [
      "All cancellation requests must be submitted in writing.",
      "Cancellations made more than 30 days prior to departure will attract a service charge of 15% of the total package value, in addition to actual supplier retention charges.",
      "Cancellations between 15 and 30 days will incur 50% of the package value.",
      "Cancellations within 15 days of travel or failure to arrive (no-show) will be treated as 100% cancellation.",
      "Travel during peak season (10 December to 20 January) is strictly non-cancellable.",
    ],
  },
  {
    id: 3,
    title: "Air Travel",
    content: [
      "Airline bookings are governed entirely by the respective airline’s fare rules.",
      "Any amendments, cancellations, or credits shall be processed strictly in accordance with airline policies.",
    ],
  },
  {
    id: 4,
    title: "Postponement & Travel Credit",
    content: [
      "In exceptional circumstances supported by valid documentation, travel postponement may be considered, provided the request is received at least 7 days prior to departure.",
      "Approved postponements will be issued as travel credit valid for up to 9 months.",
      "Any airline, hotel, transport, or supplier retention charges will be adjusted against the credit.",
      "Fare differences, if applicable, shall be payable at the time of reconfirmation.",
      "Once a postponed itinerary is reconfirmed, it becomes final and non-cancellable.",
    ],
  },
  {
    id: 5,
    title: "Hotels & Ground Services",
    content: [
      "Hotel check-in and check-out times are governed by individual hotel policies, generally between 10:00 AM and 2:00 PM.",
      "Early check-in or late check-out requests are subject to availability and hotel discretion.",
      "Transportation services are provided strictly as per the confirmed itinerary. Any additional usage beyond the itinerary may attract supplementary charges.",
      "Air-conditioning may be restricted in hilly regions or while the vehicle is stationary.",
      "Night driving is not included as part of standard services.",
    ],
  },
  {
    id: 6,
    title: "Service Disclaimer",
    content: [
      "TASK Holidays operates as a professional service facilitator for airlines, hotels, transport providers, and local suppliers.",
      "The company shall not be held liable for disruptions arising from force majeure events, weather conditions, political disturbances, strikes, natural calamities, or supplier-related operational constraints.",
      "No refunds shall be applicable for unused services arising from such circumstances.",
      "Guests are strongly encouraged to secure comprehensive travel insurance.",
    ],
  },
  {
    id: 7,
    title: "Liability & Jurisdiction",
    content: [
      "Guests are responsible for the safekeeping of personal belongings at all times.",
      "Any disputes, claims, or legal matters shall be subject exclusively to the jurisdiction of TASK Holidays.",
      "In the absence of any written objection within 48 hours of invoice or voucher issuance, it shall be deemed that the guest has reviewed and accepted these terms in full.",
    ],
  },
];

const TermsConditionsPage = () => {
  return (
    <>
      <Header navItems={[]} />
      <main className={`${styles.tnc} section_white__spacing`}>
        <section className={`${styles.tnc__hero}`}>
          <div className={`${styles.tnc__container} container `}>
            <h1 className={styles.tnc__title}>
              Premium Travel – Terms & Conditions
            </h1>
            <p className={styles.tnc__subtitle}>
              Please read these terms carefully before confirming your travel
              with TASK Holidays.
            </p>
          </div>
        </section>

        <section className={styles.tnc__content}>
          <div className={`${styles.tnc__container} container`}>
            {tncData.map((item) => (
              <div key={item.id} className={styles.tnc__block}>
                <h2 className={styles.tnc__heading}>{item.title}</h2>
                <ul className={styles.tnc__list}>
                  {item.content.map((text, index) => (
                    <li key={index}>
                      <p className={styles.tnc__text}>{text}</p>
                    </li>
                  ))}
                </ul>
              </div>
            ))}
          </div>
        </section>
      </main>
      <Footer />
    </>
  );
};

export default TermsConditionsPage;
