export const destinationImages: Record<string, string[]> = {
  andaman: [
    "andaman_taskholidays_1.jpg",
    "andaman_taskholidays_2.jpg",
    "andaman_taskholidays_3.jpg",
    "andaman_taskholidays_4.jpg",
    "andaman_taskholidays_5.jpg",
    "andaman_taskholidays_6.jpg",
    "andaman_taskholidays_7.jpg",
    "andaman_taskholidays_8.jpg",
    "andaman_taskholidays_9.jpg",
  ],

  bali: [
    "bali_taskholidays_1.jpg",
    "bali_taskholidays_2.jpg",
    "bali_taskholidays_3.jpg",
    "bali_taskholidays_4.jpg",
    "bali_taskholidays_5.jpg",
    "bali_taskholidays_6.jpg",
    "bali_taskholidays_7.jpg",
    "bali_taskholidays_8.jpg",
  ],

  dubai: [
    "dubai_taskholidays_1.jpg",
    "dubai_taskholidays_2.jpg",
    "dubai_taskholidays_3.jpg",
    "dubai_taskholidays_4.jpg",
    "dubai_taskholidays_5.jpg",
    "dubai_taskholidays_6.jpg",
    "dubai_taskholidays_7.jpg",
    "dubai_taskholidays_8.jpg",
  ],

  kerala: [
    "kerala_taskholidays_1.jpg",
    "kerala_taskholidays_2.jpg",
    "kerala_taskholidays_3.jpg",
    "kerala_taskholidays_4.jpg",
    "kerala_taskholidays_5.jpg",
    "kerala_taskholidays_6.jpg",
    "kerala_taskholidays_7.jpg",
    "kerala_taskholidays_8.jpg",
    "kerala_taskholidays_9.jpg",
    "kerala_taskholidays_10.jpg",
    "kerala_taskholidays_11.jpg",
    "kerala_taskholidays_12.jpg",
    "kerala_taskholidays_13.jpg",
    "kerala_taskholidays_14.jpg",
    "kerala_taskholidays_15.jpg",
    "kerala_taskholidays_16.jpg",
    "kerala_taskholidays_17.jpg",
  ],

  ladakh: [
    "ladakh_taskholidays_1.jpg",
    "ladakh_taskholidays_2.jpg",
    "ladakh_taskholidays_3.jpg",
    "ladakh_taskholidays_4.jpg",
    "ladakh_taskholidays_5.jpg",
    "ladakh_taskholidays_6.jpg",
    "ladakh_taskholidays_7.jpg",
    "ladakh_taskholidays_8.jpg",
    "ladakh_taskholidays_9.jpg",
    "ladakh_taskholidays_10.jpg",
    "ladakh_taskholidays_11.jpg",
    "ladakh_taskholidays_12.jpg",
    "ladakh_taskholidays_13.jpg",
    "ladakh_taskholidays_14.jpg",
  ],

  rajasthan: [
    "rajasthan_taskholidays_1.jpg",
    "rajasthan_taskholidays_2.jpg",
    "rajasthan_taskholidays_3.jpg",
    "rajasthan_taskholidays_4.jpg",
    "rajasthan_taskholidays_5.jpg",
    "rajasthan_taskholidays_6.jpg",
    "rajasthan_taskholidays_7.jpg",
    "rajasthan_taskholidays_8.jpg",
    "rajasthan_taskholidays_9.jpg",
  ],
};
