export const destinationImages: Record<string, string[]> = {
  andaman: [
    "andaman_taskholidays_1_siucth",
    "andaman_taskholidays_2_ophsci",
    "andaman_taskholidays_3_owutdv",
    "andaman_taskholidays_4_jmyoga",
    "andaman_taskholidays_5_y5feok",
    "andaman_taskholidays_6_x9l5uv",
    "andaman_taskholidays_7_rmmvf4",
    "andaman_taskholidays_8_utekmr",
    "andaman_taskholidays_9_elz0lt",
  ],

  bali: [
    "bali_taskholidays_1_hz0btw",
    "bali_taskholidays_2_tlfcoa",
    "bali_taskholidays_3_art0qb",
    "bali_taskholidays_4_t94gwe",
    "bali_taskholidays_5_a3e5yy",
    "bali_taskholidays_6_z1fsh9",
    "bali_taskholidays_7_esncvx",
    "bali_taskholidays_8_lyp1ov",
  ],

  dubai: [
    "dubai_taskholidays_1_ci1o1t",
    "dubai_taskholidays_2_zncwov",
    "dubai_taskholidays_3_rmht2j",
    "dubai_taskholidays_4_ngxjeq",
    "dubai_taskholidays_5_ux4ppm",
    "dubai_taskholidays_6_z6ogko",
    "dubai_taskholidays_7_qy2bwz",
    "dubai_taskholidays_8_gybt6u",
  ],

  kerala: [
    "kerala_taskholidays_1_htw5zi",
    "kerala_taskholidays_2_b4yaeu",
    "kerala_taskholidays_3_soaec4",
    "kerala_taskholidays_4_eytsho",
    "kerala_taskholidays_5_ebrxcm",
    "kerala_taskholidays_6_kwo9nd",
    "kerala_taskholidays_7_arlisw",
    "kerala_taskholidays_8_apkpsd",
    "kerala_taskholidays_9_jbhemx",
    "kerala_taskholidays_10_rbh3cw",
    "kerala_taskholidays_11_woo8oo",
    "kerala_taskholidays_12_iuyjhr",
    "kerala_taskholidays_13_c8yjad",
    "kerala_taskholidays_14_zcnrdg",
    "kerala_taskholidays_15_gomvbl",
    "kerala_taskholidays_16_de3imz",
    "kerala_taskholidays_17_ue8yow",
  ],

  ladakh: [
    "ladakh_taskholidays_1_ywmjpn",
    "ladakh_taskholidays_2_j2mbiv",
    "ladakh_taskholidays_3_a5fp9p",
    "ladakh_taskholidays_4_r9ckw9",
    "ladakh_taskholidays_5_qnhwbt",
    "ladakh_taskholidays_6_fpynpz",
    "ladakh_taskholidays_7_v9karv",
    "ladakh_taskholidays_8_ktjzxb",
    "ladakh_taskholidays_9_pnanxx",
    "ladakh_taskholidays_10_umon07",
    "ladakh_taskholidays_11_e4dhik",
    "ladakh_taskholidays_12_optowq",
    "ladakh_taskholidays_13_pput1s",
    "ladakh_taskholidays_14_ke3ng7",
  ],

  rajasthan: [
    "rajasthan_taskholidays_1_ljevof",
    "rajasthan_taskholidays_2_histvx",
    "rajasthan_taskholidays_3_rsmhcc",
    "rajasthan_taskholidays_4_c3zsnk",
    "rajasthan_taskholidays_5_ujipon",
    "rajasthan_taskholidays_6_wyljrq",
    "rajasthan_taskholidays_7_wywu8r",
    "rajasthan_taskholidays_8_eu5xjk",
    "rajasthan_taskholidays_9_wozwg9",
  ],
};
